Repository Py-Contributors/AudioBook, pull requests merged in 2022-10, with the labels that each got.

#8 :hammer: Refactoring code and improving navigation functionality
  Pipfile
  Pipfile.lock
  audiobook/__init__.py
  audiobook/main.py
Labels: hacktoberfest-accepted

#13 featute: audiobook can be saved now
  README.md
  audiobook/main.py
Labels: enhancement, hacktoberfest-accepted

#19 Feature: Epub file support added
  .github/workflows/auto_assign.yaml
  .github/workflows/python-app.yml
  README.md
  audiobook/__init__.py
  audiobook/config.py
  audiobook/main.py
  audiobook/utils.py
  requirements.txt
  tests/test_audiobook.py
Labels: enhancement

#22 feature: Load book from library
  .github/workflows/python-app.yml
  audiobook/__init__.py
  audiobook/main.py
  audiobook/utils.py
Labels: enhancement, hacktoberfest-accepted

#20 Feature: Add support to read/save web articles(audio)
  audiobook/__init__.py
  audiobook/article_web_scraper.py
  audiobook/main.py
  requirements.txt
  tests/test_audiobook.py
Labels: enhancement, hacktoberfest-accepted

#40 Feature: docs/docx file support adding
  audiobook/config.py
  audiobook/main.py
  audiobook/utils.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#43 Make flake8 happy
  audiobook/__init__.py
  audiobook/article_web_scraper.py
  audiobook/config.py
  audiobook/main.py
  audiobook/utils.py
  tests/test_audiobook.py
Labels: enhancement, hacktoberfest-accepted

#57 Feature: ODT files support for audiobook as mentioned in issues
  audiobook/main.py
  audiobook/utils.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted, ready-for-review

#65 adding pytest workflow
  .github/workflows/add_labels.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/python-app.yml
  .github/workflows/run-pytest.yaml
Labels: enhancement
